### ISSUE TITLE
Early end on single survivor

### ISSUE THREAD

**Issue by Blauelf** [CodinGame/MeanMax#1]
Maybe it's me not understanding the Java stream API (I've done Java 1.4 many years ago), but on

https://github.com/CodinGame/MeanMax/blob/93dcc348d9efed01e6fadfe24fa9de0b024f87a9/Referee.java#L1466-L1467

instead of

`return players.stream().filter(p -> p != alive).anyMatch(p -> p.score > survivor.score);`

which I think means "any dead player has higher score", shouldn't it be

`return players.stream().filter(p -> p != alive).allMatch(p -> p.score < survivor.score);`

for "all dead players have lower score", or

`return players.stream().filter(p -> p != alive).noneMatch(p -> p.score >= survivor.score);`

for "none of the dead players has the same or higher score", to match the comment?

**Comment by JeanDamien** [comment]
@chickentuna made a PR and we accepted it. Thanks for the report.
